# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        pip install .
        pip install .[test]
    - name: Lint with flake8
      run: |
        # Check syntax errors
        flake8 yucca --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run black
      run: |
        black --check --verbose yucca
    - name: Test with pytest
      run: |
        pytest
